.TH "BZH_VIE.c" 3 "Wed Jan 20 2021" "T2R" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BZH_VIE.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'TicketToRideAPI\&.h'\fP
.br
\fC#include 'move\&.h'\fP
.br
\fC#include 'game\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBOTNAME\fP   'BZH_VIE'"
.br
.ti -1c
.RI "#define \fBNB_CITY_MAX\fP   '36'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdisplayObjs\fP (\fBt_game\fP *G)"
.br
.RI "to show some infos about my data into the terminal which are filled into the \fBt_game\fP G which contains everything "
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "connect to the server and play the moves "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BOTNAME   'BZH_VIE'"

.PP
Definition at line 7 of file BZH_VIE\&.c\&.
.SS "#define NB_CITY_MAX   '36'"

.PP
Definition at line 8 of file BZH_VIE\&.c\&.
.SH "Function Documentation"
.PP 
.SS "void displayObjs (\fBt_game\fP * G)"

.PP
to show some infos about my data into the terminal which are filled into the \fBt_game\fP G which contains everything 
.PP
\fBParameters\fP
.RS 4
\fI\fBt_game\fP\fP *G 
.RE
.PP

.PP
Definition at line 38 of file BZH_VIE\&.c\&.
.SS "int main ()"

.PP
connect to the server and play the moves 
.PP
Definition at line 65 of file BZH_VIE\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for T2R from the source code\&.
