.TH "game.h" 3 "Wed Jan 20 2021" "T2R" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game.h
.SH SYNOPSIS
.br
.PP
\fC#include 'TicketToRideAPI\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBt_track\fP"
.br
.ti -1c
.RI "struct \fBt_player\fP"
.br
.ti -1c
.RI "struct \fBt_game\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for T2R from the source code\&.
