.TH "t_chooseObjectives" 3 "Wed Jan 20 2021" "T2R" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_chooseObjectives
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TicketToRideAPI\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnbObjectives\fP"
.br
.ti -1c
.RI "int \fBchosen\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 92 of file TicketToRideAPI\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int chosen[3]"

.PP
Definition at line 94 of file TicketToRideAPI\&.h\&.
.SS "int nbObjectives"

.PP
Definition at line 93 of file TicketToRideAPI\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for T2R from the source code\&.
