.TH "t_claimRouteMove" 3 "Wed Jan 20 2021" "T2R" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_claimRouteMove
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TicketToRideAPI\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcity1\fP"
.br
.ti -1c
.RI "int \fBcity2\fP"
.br
.ti -1c
.RI "\fBt_color\fP \fBcolor\fP"
.br
.ti -1c
.RI "int \fBnbLocomotives\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 69 of file TicketToRideAPI\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int city1"

.PP
Definition at line 70 of file TicketToRideAPI\&.h\&.
.SS "int city2"

.PP
Definition at line 70 of file TicketToRideAPI\&.h\&.
.SS "\fBt_color\fP color"

.PP
Definition at line 71 of file TicketToRideAPI\&.h\&.
.SS "int nbLocomotives"

.PP
Definition at line 72 of file TicketToRideAPI\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for T2R from the source code\&.
