.TH "t_drawBlindCard" 3 "Wed Jan 20 2021" "T2R" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_drawBlindCard
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TicketToRideAPI\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBt_color\fP \fBcard\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 82 of file TicketToRideAPI\&.h\&.
.SH "Field Documentation"
.PP 
.SS "\fBt_color\fP card"

.PP
Definition at line 83 of file TicketToRideAPI\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for T2R from the source code\&.
