.TH "t_game" 3 "Wed Jan 20 2021" "T2R" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_game
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [20]"
.br
.ti -1c
.RI "\fBt_color\fP \fBfaceUp\fP [5]"
.br
.ti -1c
.RI "int \fBplayer\fP"
.br
.ti -1c
.RI "\fBt_player\fP \fBplayers\fP [2]"
.br
.ti -1c
.RI "int \fBnbCities\fP"
.br
.ti -1c
.RI "int \fBnbTracks\fP"
.br
.ti -1c
.RI "\fBt_objective\fP \fBtamp\fP [3]"
.br
.ti -1c
.RI "\fBt_track\fP \fBtabTracks2D\fP [36][36]"
.br
.ti -1c
.RI "\fBt_track\fP \fBtabTracks\fP [78]"
.br
.ti -1c
.RI "int \fBindice\fP"
.br
.ti -1c
.RI "int \fBprec\fP [36]"
.br
.ti -1c
.RI "int \fBD\fP [36]"
.br
.ti -1c
.RI "int \fBchemin\fP [100]"
.br
.ti -1c
.RI "\fBt_track\fP \fBlastTrack\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file game\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int chemin[100]"

.PP
Definition at line 38 of file game\&.h\&.
.SS "int D[36]"

.PP
Definition at line 37 of file game\&.h\&.
.SS "\fBt_color\fP faceUp[5]"

.PP
Definition at line 28 of file game\&.h\&.
.SS "int indice"

.PP
Definition at line 35 of file game\&.h\&.
.SS "\fBt_track\fP lastTrack"

.PP
Definition at line 39 of file game\&.h\&.
.SS "char name[20]"

.PP
Definition at line 27 of file game\&.h\&.
.SS "int nbCities"

.PP
Definition at line 31 of file game\&.h\&.
.SS "int nbTracks"

.PP
Definition at line 31 of file game\&.h\&.
.SS "int player"

.PP
Definition at line 29 of file game\&.h\&.
.SS "\fBt_player\fP players[2]"

.PP
Definition at line 30 of file game\&.h\&.
.SS "int prec[36]"

.PP
Definition at line 36 of file game\&.h\&.
.SS "\fBt_track\fP tabTracks[78]"

.PP
Definition at line 34 of file game\&.h\&.
.SS "\fBt_track\fP tabTracks2D[36][36]"

.PP
Definition at line 33 of file game\&.h\&.
.SS "\fBt_objective\fP tamp[3]"

.PP
Definition at line 32 of file game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for T2R from the source code\&.
