.TH "t_player" 3 "Wed Jan 20 2021" "T2R" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_player
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP [20]"
.br
.ti -1c
.RI "int \fBnbWagons\fP"
.br
.ti -1c
.RI "int \fBnbCards\fP"
.br
.ti -1c
.RI "int \fBcards\fP [10]"
.br
.ti -1c
.RI "int \fBnbObjectives\fP"
.br
.ti -1c
.RI "\fBt_objective\fP \fBobjectives\fP [20]"
.br
.ti -1c
.RI "\fBt_track\fP \fBtracks2take\fP [100]"
.br
.ti -1c
.RI "int \fBnbTracks2take\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file game\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int cards[10]"

.PP
Definition at line 19 of file game\&.h\&.
.SS "char name[20]"

.PP
Definition at line 16 of file game\&.h\&.
.SS "int nbCards"

.PP
Definition at line 18 of file game\&.h\&.
.SS "int nbObjectives"

.PP
Definition at line 20 of file game\&.h\&.
.SS "int nbTracks2take"

.PP
Definition at line 23 of file game\&.h\&.
.SS "int nbWagons"

.PP
Definition at line 17 of file game\&.h\&.
.SS "\fBt_objective\fP objectives[20]"

.PP
Definition at line 21 of file game\&.h\&.
.SS "\fBt_track\fP tracks2take[100]"

.PP
Definition at line 22 of file game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for T2R from the source code\&.
