.TH "t_track" 3 "Wed Jan 20 2021" "T2R" \" -*- nroff -*-
.ad l
.nh
.SH NAME
t_track
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <game\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcity1\fP"
.br
.ti -1c
.RI "int \fBcity2\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "\fBt_color\fP \fBcolor1\fP"
.br
.ti -1c
.RI "\fBt_color\fP \fBcolor2\fP"
.br
.ti -1c
.RI "int \fBtaken\fP"
.br
.ti -1c
.RI "int \fBme\fP"
.br
.ti -1c
.RI "int \fBmulti\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file game\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int city1"

.PP
Definition at line 7 of file game\&.h\&.
.SS "int city2"

.PP
Definition at line 7 of file game\&.h\&.
.SS "\fBt_color\fP color1"

.PP
Definition at line 9 of file game\&.h\&.
.SS "\fBt_color\fP color2"

.PP
Definition at line 9 of file game\&.h\&.
.SS "int length"

.PP
Definition at line 8 of file game\&.h\&.
.SS "int me"

.PP
Definition at line 11 of file game\&.h\&.
.SS "int multi"

.PP
Definition at line 12 of file game\&.h\&.
.SS "int taken"

.PP
Definition at line 10 of file game\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for T2R from the source code\&.
